# Generated by Django 5.0.7 on 2024-07-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created', 'updated']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='crreated',
            new_name='created',
        ),
    ]
